"""Quiz schemas for API and AI generation."""

from typing import List, Optional
from pydantic import BaseModel, Field


class QuestionGenerationSchema(BaseModel):
    """Schema for a single question generated by AI."""

    question: str = Field(..., description="The question text")
    option_1: str = Field(..., description="First option")
    option_2: str = Field(..., description="Second option")
    option_3: str = Field(..., description="Third option")
    option_4: str = Field(..., description="Fourth option")
    correct_option_index: int = Field(
        ..., description="Index of the correct option (1-4)", ge=1, le=4
    )
    explanation: str = Field(
        ..., description="Explanation for why the correct option is correct"
    )


class QuizGenerationSchema(BaseModel):
    """Schema for a quiz generated by AI."""

    questions: List[QuestionGenerationSchema] = Field(
        ..., description="List of questions for the quiz"
    )
    duration_seconds: Optional[int] = Field(
        None, description="Recommended duration for the quiz in seconds"
    )
    passing_score_ratio: float = Field(
        0.7, description="Passing score ratio (0.0 to 1.0)", ge=0.0, le=1.0
    )


class QuestionResponse(BaseModel):
    """Schema for a single question response."""

    id: int
    question: str
    option_1: str
    option_2: str
    option_3: str
    option_4: str
    explanation: Optional[str] = None
    # Note: correct_option_index is hidden in user-facing response if needed,
    # but for now we include it or handle it in a separate 'check' endpoint.
    correct_option_index: int

    class Config:
        from_attributes = True


class QuizResponse(BaseModel):
    """Schema for a quiz response."""

    id: int
    lesson_id: int
    duration: Optional[int] = None
    passing_score: float
    questions: List[QuestionResponse] = []

    class Config:
        from_attributes = True
